// <auto-generated />
using HasDataNewLineRepro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HasDataNewLineRepro.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20180711194150_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HasDataNewLineRepro.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<double>("Price");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new { Id = 1, Description = @"
<div>
  <p>This is a scarf and all that goes with that.</p>
</div>", Price = 19.99, Title = "Scarf Works" },
                        new { Id = 2, Description = "<div>
<p>This is a scarf and all that goes with that.</p>
</div>", Price = 19.99, Title = "Belt Doesn't" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
